- name: Include user tasks
  ansible.builtin.include_tasks:
    file: user.yml

- name: Include hardening tasks
  ansible.builtin.include_tasks:
    file: hardening.yml

- name: Include sysctl kernel hardening tasks
  ansible.builtin.include_tasks:
    file: sysctl.yml

- name: Include software tasks
  ansible.builtin.include_tasks:
    file: software.yml
