- name: Set language to English
  community.general.locale_gen:
    name: "en_US.UTF-8"
    state: present

- name: Allow admin user passwordless sudo
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ admin_user }}"
    content: "{{ admin_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"

- name: Ensure admin user exists
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: /bin/bash
    create_home: true
    password: "{{ admin_password }}"
